# Dedicated Dockerfile for Jojira Duffel Azure Service Bus Order Processor Service Container
FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1 \
    PYTHONPATH=/app/src

WORKDIR /app

# Install system dependencies & Python packages
COPY requirements.txt ./requirements.txt
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copy application code base and configuration
COPY . .

# Run the Order Processor Worker Loop
CMD ["python", "run_processor.py"]
